export const mockData = [
    {
      id: 1,
      ref: "APP-001234",
      firstName: "John",
      lastName: "Doe",
      email: "john.doe@example.com",
      amount: "$15,000",
      status: "Pending",
      dateApplied: "2023-09-12",
    },
    {
      id: 2,
      ref: "APP-001235",
      firstName: "Jane",
      lastName: "Smith",
      email: "jane.smith@example.com",
      amount: "$22,500",
      status: "Approved",
      dateApplied: "2023-09-10",
    },
    {
      id: 3,
      ref: "APP-001236",
      firstName: "Michael",
      lastName: "Brown",
      email: "michael.brown@example.com",
      amount: "$5,000",
      status: "Declined",
      dateApplied: "2023-09-15",
    },
    {
      id: 4,
      ref: "APP-001237",
      firstName: "Emily",
      lastName: "Johnson",
      email: "emily.johnson@example.com",
      amount: "$12,000",
      status: "Pending",
      dateApplied: "2023-09-18",
    },
    {
      id: 5,
      ref: "APP-001238",
      firstName: "David",
      lastName: "Williams",
      email: "david.williams@example.com",
      amount: "$10,500",
      status: "Approved",
      dateApplied: "2023-09-20",
    },
    {
      id: 6,
      ref: "APP-001239",
      firstName: "Sophia",
      lastName: "Davis",
      email: "sophia.davis@example.com",
      amount: "$8,700",
      status: "Pending",
      dateApplied: "2023-09-22",
    },
    {
      id: 7,
      ref: "APP-001240",
      firstName: "Daniel",
      lastName: "Garcia",
      email: "daniel.garcia@example.com",
      amount: "$19,000",
      status: "Approved",
      dateApplied: "2023-09-25",
    },
    {
      id: 8,
      ref: "APP-001241",
      firstName: "Olivia",
      lastName: "Martinez",
      email: "olivia.martinez@example.com",
      amount: "$25,300",
      status: "Declined",
      dateApplied: "2023-09-27",
    },
    {
      id: 9,
      ref: "APP-001242",
      firstName: "Ethan",
      lastName: "Hernandez",
      email: "ethan.hernandez@example.com",
      amount: "$13,800",
      status: "Pending",
      dateApplied: "2023-09-29",
    },
    {
      id: 10,
      ref: "APP-001243",
      firstName: "Liam",
      lastName: "Lopez",
      email: "liam.lopez@example.com",
      amount: "$18,200",
      status: "Approved",
      dateApplied: "2023-09-30",
    },
  ];
  